/* A servlet to display the contents of the MySQL movieDB database */

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletResponse;

public class navBar extends HttpServlet {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public String getServletInfo() {
		return "navbar";
	}

	// Use http GET

	public static void doGet(HttpServletResponse response) throws IOException,
			ServletException {
		response.setContentType("text/html"); // Response mime type

		// Output stream to STDOUT
		PrintWriter out = response.getWriter();

		out.println("<!DOCTYPE html>");
		out.println("<html lang=\"en-gb\" dir=\"ltr\">");
		out.println("<head>");
		out.println("<title></title>");
		out.println("<link rel=\"stylesheet\" href=\"css/uikit.gradient.css\" />");
		out.println("<script");
		out.println("	src=\"http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js\"></script>");
		out.println("<script src=\"js/uikit.min.js\"></script>");
		// ///////////TOOLTIP////////////////
		out.println("<style type=\"text/css\">");
		out.println("div#tipDiv {");
		out.println("    font-size:11px; line-height:1.2;");
		out.println("    color:#000; background-color:#E1E5F1; ");
		out.println("    border:1px solid #667295; padding:4px;");
		out.println("    width:280px; ");
		out.println("}");
		out.println("");
		out.println("/* example demonstrating applying styles to content inside 'tipContent' for tooltip display */");
		out.println("div#tipDiv ul.tipContentList {");
		out.println("    margin: .5em 0 1em 2em;");
		out.println("    padding:0;");
		out.println("}");
		out.println("");
		out.println("</style>");
		out.println("<script src=\"js/dw_tooltip_c.js\" type=\"text/javascript\"></script>");
		out.println("<script type=\"text/javascript\">");
		out.println("dw_Tooltip.defaultProps = {");
		out.println("    //supportTouch: true, // set false by default");
		out.println("    content_source: 'class_id' // class holds id of element with tooltip content");
		out.println("}");
		out.println("");
		out.println("// Problems, errors? See http://www.dyn-web.com/tutorials/obj_lit.php#syntax");
		out.println("");
		out.println("// Write style rule that hides elements with tipContent class for capable browsers ");
		out.println("dw_Tooltip.writeStyleRule();");
		out.println("");
		out.println("</script>");
		// ///////////END TOOLTIP/////////////
		out.println("</head>");
		out.println("");
		out.println("<body>");
		out.println("<script language=\"javascript\" type=\"text/javascript\">");
		out.println("<!--");
		out.println("//Browser Support Code");
		out.println("function ajaxFunction(str)");
		out.println("{");
		out.println("	if (str.length==0)");
		out.println("		{");
		out.println("		document.getElementById(\"livesearch\").innerHTML=\"\";");
		out.println("		document.getElementById(\"livesearch\").style.border=\"0px\";");
		out.println("		return;");
		out.println("		}");
		out.println("	var ajaxRequest;  // The variable that makes Ajax possible!");
		out.println("");
		out.println("	try{");
		out.println("		// Opera 8.0+, Firefox, Safari");
		out.println("		ajaxRequest = new XMLHttpRequest();");
		out.println("	} catch (e){");
		out.println("		// Internet Explorer Browsers");
		out.println("		try{");
		out.println("			ajaxRequest = new ActiveXObject(\"Msxml2.XMLHTTP\");");
		out.println("		} catch (e) {");
		out.println("			try{");
		out.println("				ajaxRequest = new ActiveXObject(\"Microsoft.XMLHTTP\");");
		out.println("			} catch (e){");
		out.println("				// Something went wrong");
		out.println("				alert(\"Your browser broke!\");");
		out.println("				return false;");
		out.println("			}");
		out.println("		}");
		out.println("	}");
		out.println("	// Create a function that will receive data sent from the server");
		out.println("	ajaxRequest.onreadystatechange = function(){");
		out.println("		if(ajaxRequest.readyState == 4){");
		out.println("			document.getElementById(\"livesearch\").innerHTML=ajaxRequest.responseText;");
		out.println("			document.getElementById(\"livesearch\").style.border=\"1px solid #A5ACB2\";");
		out.println("		}");
		out.println("	}");
		out.println("	ajaxRequest.open(\"GET\", \"liveSearch?movie=\"+str, true);");
		out.println("	ajaxRequest.send();");
		out.println("}");
		out.println("");
		out.println("//-->");
		out.println("</script>");
		// //////////////////////////////MOVIE POP
		// SCRIPT////////////////////////////////////////
		out.println("<script language=\"javascript\" type=\"text/javascript\">");
		out.println("<!--");
		out.println("//Browser Support Code");
		out.println("function moviePop(str)");
		out.println("{");
		out.println("	var ajaxRequest;  // The variable that makes Ajax possible!");
		out.println("");
		out.println("	try{");
		out.println("		// Opera 8.0+, Firefox, Safari");
		out.println("		ajaxRequest = new XMLHttpRequest();");
		out.println("	} catch (e){");
		out.println("		// Internet Explorer Browsers");
		out.println("		try{");
		out.println("			ajaxRequest = new ActiveXObject(\"Msxml2.XMLHTTP\");");
		out.println("		} catch (e) {");
		out.println("			try{");
		out.println("				ajaxRequest = new ActiveXObject(\"Microsoft.XMLHTTP\");");
		out.println("			} catch (e){");
		out.println("				// Something went wrong");
		out.println("				alert(\"Your browser broke!\");");
		out.println("				return false;");
		out.println("			}");
		out.println("		}");
		out.println("	}");
		out.println("	// Create a function that will receive data sent from the server");
		out.println("	ajaxRequest.onreadystatechange = function(){");
		out.println("		if(ajaxRequest.readyState == 4){");
		out.println("			document.getElementById(\"moviepop\").innerHTML=ajaxRequest.responseText;");
		out.println("			document.getElementById(\"moviepop\").style.border=\"1px solid #A5ACB2\";");
		out.println("		}");
		out.println("	}");
		out.println("	ajaxRequest.open(\"GET\", \"moviePop?movie=\"+str, true);");
		out.println("	ajaxRequest.send();");
		out.println("}");
		out.println("");
		out.println("//-->");
		out.println("</script>");
		out.println("	<div class=\"uk-grid\">");
		out.println("		<div class=\"uk-width-1-1\">");
		out.println("			<nav class=\"uk-navbar\">");
		out.println("				<a class=\"uk-navbar-brand uk-hidden-small\" href=\"home.html\">Patflix</a>");
		out.println("				<ul class=\"uk-navbar-nav uk-hidden-small\">");
		out.println("					<!--begin adv search-->");
		out.println("					<li class=\"uk-navbar-nav\" data-uk-offcanvas=\"{target:'#adv-srch'}\"><a");
		out.println("						href=\"#\">Adv. Search</a></li>");
		out.println("					<div id=\"adv-srch\" class=\"uk-offcanvas\">");
		out.println("						<div class=\"uk-offcanvas-bar\">");
		out.println("							<ul class=\"uk-nav uk-nav-offcanvas uk-nav-parent-icon\"");
		out.println("								data-uk-nav>");
		out.println("								<li class=\"uk-parent\"><a href=\"#\">Stars With</a>");
		out.println("									<ul class=\"uk-subnav uk-nav-dropdown\">");
		out.println("										<li><a href=\"#\">0-9</a>");
		out.println("											<ul class=\"uk-nav-sub\">");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=0&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">0</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=1&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">1</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=2&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">2</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=3&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">3</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=4&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">4</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=5&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">5</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=6&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">6</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=7&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">7</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=8&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">8</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=9&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">9</a></li>");
		out.println("											</ul></li>");
		out.println("										<li><a href=\"#\">A-J</a>");
		out.println("											<ul class=\"uk-nav-sub\">");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=a&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">A</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=b&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">B</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=c&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">C</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=d&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">D</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=e&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">E</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=f&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">F</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=g&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">G</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=h&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">H</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=i&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">I</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=j&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">J</a></li>");
		out.println("											</ul></li>");
		out.println("										<li><a href=\"#\">K-T</a>");
		out.println("											<ul class=\"uk-nav-sub\">");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=k&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">K</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=l&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">L</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=m&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">M</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=n&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">N</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=o&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">O</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=p&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">P</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=q&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Q</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=r&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">R</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=s&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">S</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=t&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">T</a></li>");
		out.println("											</ul></li>");
		out.println("										<li><a href=\"#\">U-Z</a>");
		out.println("											<ul class=\"uk-nav-sub\">");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=u&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">U</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=v&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">V</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=w&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">W</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=x&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">X</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=y&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Y</a></li>");
		out.println("												<li><a");
		out.println("													href=\"SearchFirstLetter?by=title&amp;movie=z&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Z</a></li>");
		out.println("												<li><a href=\"#\"><BR> </a></li>");
		out.println("												<li><a href=\"#\"><BR> </a></li>");
		out.println("												<li><a href=\"#\"><BR> </a></li>");
		out.println("												<li><a href=\"#\"><BR> </a></li>");
		out.println("											</ul></li>");
		out.println("									</ul></li>");
		out.println("								<li class=\"uk-parent\"><a href=\"#\">Genre is</a>");
		out.println("									<ul class=\"uk-nav-sub\">");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Action&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Action</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Adventure&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Adventure</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Animation&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Animation</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Comedy&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Comedy</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Crime&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Crime</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Documentary&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Documentary</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Drama&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Drama</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Family&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Family</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Fantasy&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Fantasy</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Film-Noir&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Film-Noir</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Horror&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Horror</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Music&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Music</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Musical&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Musical</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Mystery&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Mystery</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Romance&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Romance</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Sci-Fi&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Sci-Fi</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Thriller&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Thriller</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=War&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">War</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Western&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Western</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=SCI/FI&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">SCI/FI</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Crime/Gangster&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Crime/Gangster</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Epics/Historical&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Epics/Historical</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Musicals&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Musicals</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Science Fiction&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Science");
		out.println("												Fiction</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Westerns&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Westerns</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Science Fiction/Fantasy&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Science");
		out.println("												Fiction/Fantasy</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Musical/Performing Arts&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Musical/Performing");
		out.println("												Arts</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=spy&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">spy</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=James Bond&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">James");
		out.println("												Bond</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Short&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Short</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Epics/Historial&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Epics/Historial</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Coming-of-Age-Drama&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Coming-of-Age-Drama</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Detective&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Detective</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Gangster&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Gangster</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Love&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Love</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=epics&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">epics</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Foreign&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Foreign</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Romance&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Romance</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Roman&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Roman</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Tragedy&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Tragedy</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=SciFi&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">SciFi</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=classic&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">classic</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=adventure&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">adventure</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=kid&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">kid</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=musial&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">musial</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=arts&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">arts</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Suspense&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Suspense</a></li>");
		out.println("										<li><a");
		out.println("											href=\"SearchGenre?by=genre&amp;genre=Indie&amp;order=title&amp;type=asc&amp;page=0&amp;rpp=5\">Indie</a></li>");
		out.println("									</ul></li>");
		out.println("							</ul>");
		out.println("						</div>");
		out.println("					</div>");
		out.println("					<!--end adv search-->");
		out.println("					<!--begin admin panel-->");
		out.println("					<div id=\"admin-login\" class=\"uk-modal\">");
		out.println("						<div class=\"uk-modal-dialog\">");
		out.println("							<!--login goes here-->");
		out.println("							<a href=\"\" class=\"uk-modal-close uk-close\"></a>");
		out.println("							<h3>Admin Login</h3>");
		out.println("							<form class=\"uk-form\" data-uk-margin action=\"AdminLoginForm\"");
		out.println("								method=\"POST\">");
		out.println("								<div class=\"uk-form-icon\">");
		out.println("									<i class=\"uk-icon-user\"></i> <input type=\"text\" name=\"email\">");
		out.println("								</div>");
		out.println("								<BR>");
		out.println("								<div class=\"uk-form-icon\">");
		out.println("									<i class=\"uk-icon-key\"></i> <input type=\"password\"");
		out.println("										name=\"password\">");
		out.println("								</div>");
		out.println("								<BR> <input class=\"uk-button\" type=\"submit\" value=\"Login\">");
		out.println("							</form>");
		out.println("							<!--end login-->");
		out.println("						</div>");
		out.println("					</div>");
		out.println("					<!--data-uk-offcanvas=\"{target:'#admin-panel'}\"-->");
		out.println("					<div id=\"admin-panel\" class=\"uk-offcanvas\">");
		out.println("						<div class=\"uk-offcanvas-bar\">");
		out.println("							<ul class=\"uk-nav uk-nav-offcanvas uk-nav-parent-icon\"");
		out.println("								data-uk-nav>");
		out.println("								<li class=\"uk-nav-header\">Admin Panel</li>");
		out.println("								<li class=\"uk-parent\"><a href=\"admin.html\"><i");
		out.println("										class=\"uk-icon-home\"></i> Dashboard</a></li>");
		out.println("								<li class=\"uk-nav-header\">DB Management</li>");
		out.println("								<li class=\"uk-parent\"><a href=\"#\"><i");
		out.println("										class=\"uk-icon-video-camera\"></i> Movies</a>");
		out.println("									<ul class=\"uk-nav-sub\">");
		out.println("										<li><a href=\"addMovie?\"><i");
		out.println("												class=\"uk-icon-plus-circle\"></i> Add Movie</a></li>");
		out.println("										<li><a href=\"\"><i class=\"uk-icon-cog\"></i> Modify");
		out.println("												Movie</a></li>");
		out.println("										<li><a href=\"\"><i class=\"uk-icon-minus-circle\"></i>");
		out.println("												Delete Movie</a></li>");
		out.println("									</ul></li>");
		out.println("");
		out.println("								<li class=\"uk-parent\"><a href=\"#\"><i");
		out.println("										class=\"uk-icon-star\"></i> Stars</a>");
		out.println("									<ul class=\"uk-nav-sub\">");
		out.println("										<li><a href=\"addStar?\"><i class=\"uk-icon-plus-circle\"></i>");
		out.println("												Add Star</a></li>");
		out.println("										<li><a href=\"\"><i class=\"uk-icon-cog\"></i> Modify");
		out.println("												Star</a></li>");
		out.println("										<li><a href=\"\"><i class=\"uk-icon-minus-circle\"></i>");
		out.println("												Delete Star</a></li>");
		out.println("									</ul></li>");
		out.println("");
		out.println("								<li class=\"uk-parent\"><a href=\"#\"><i");
		out.println("										class=\"uk-icon-tag\"></i> Genres</a>");
		out.println("									<ul class=\"uk-nav-sub\">");
		out.println("										<li><a href=\"addGenre?\"><i");
		out.println("												class=\"uk-icon-plus-circle\"></i> Add Genre</a></li>");
		out.println("										<li><a href=\"\"><i class=\"uk-icon-cog\"></i> Modify");
		out.println("												Genre</a></li>");
		out.println("										<li><a href=\"\"><i class=\"uk-icon-minus-circle\"></i>");
		out.println("												Delete Genre</a></li>");
		out.println("									</ul></li>");
		out.println("								<li class=\"uk-nav-header\">User Management</li>");
		out.println("");
		out.println("								<li><a href=\"manageUsers?\"><i class=\"uk-icon-users\"></i>");
		out.println("										Users</a></li>");
		out.println("								<li><a href=\"\"><i class=\"uk-icon-gears\"></i>");
		out.println("										Permissions</a></li>");
		out.println("");
		out.println("								<li class=\"uk-nav-header\">Reports</li>");
		out.println("								<li class=\"uk-parent\"><a href=\"#\"><i");
		out.println("												class=\"uk-icon-bug\"></i> DB Error Reports</a>");
		out.println("									<ul class=\"uk-nav-sub\">");
		out.println("										<li><a href=\"dbReports?report=moviesWithoutStar\">Movies w/o Stars</a></li>");
		out.println("										<li><a href=\"dbReports?report=starsWithoutMovie\">Stars w/o Movies</a></li>");
		out.println("										<li><a href=\"dbReports?report=moviesWithoutGenre\">Movies w/o Genres</a></li>");
		out.println("										<li><a href=\"dbReports?report=genresWithoutMovie\">Genres w/o Movies</a></li>");
		out.println("										<li><a href=\"dbReports?report=starsWithoutName\">Stars w/o Name</a></li>");
		out.println("										<li><a href=\"dbReports?report=expiredCreditCards\">Expired Credit Cards</a></li>");
		out.println("										<li><a href=\"dbReports?report=dupeMovies\">Duplicate Movies</a></li>");
		out.println("										<li><a href=\"dbReports?report=dupeStars\">Duplicate Stars</a></li>");
		out.println("										<li><a href=\"dbReports?report=dupeGenres\">Duplicate Genres</a></li>");
		out.println("										<li><a href=\"dbReports?report=dateChecker\">Date Errors</a></li>");
		out.println("										<li><a href=\"dbReports?report=emailChecker\">Email Errors</a></li>");
		out.println("									</ul>");
		out.println("								</li>");
		out.println("								<li><a href=\"\"><i class=\"uk-icon-warning\"></i> Crash");
		out.println("										Reports</a></li>");
		out.println("							</ul>");
		out.println("						</div>");
		out.println("					</div>");
		out.println("					<!--end admin panel-->");
		out.println("					<!--begin about button-->");
		out.println("					<li class=\"uk-parent\" data-uk-dropdown><a href=\"#\">About</a>");
		out.println("						<div class=\"uk-dropdown uk-dropdown-navbar\">");
		out.println("							<div class=\"uk-panel\">");
		out.println("								CS 122B Project <br> Usman Majid <br> Patrick Nguyen");
		out.println("							</div>");
		out.println("						</div></li>");
		out.println("					<!--end about button-->");
		out.println("				</ul>");
		out.println("				<div class=\"uk-navbar-content uk-navbar-flip  uk-hidden-small\">");
		out.println("					<div class=\"uk-button-group\">");
		out.println("						<a class=\"uk-button uk-button-danger\" href=\"#\">View Cart</a>");
		out.println("						<form class=\"uk-form\" action=\"Checkout\" method=\"GET\">");
		out.println("							<button type=\"submit\" class=\"uk-button uk-button-danger\">Checkout</button>");
		out.println("						</form>");
		out.println("					</div>");
		out.println("					<!-- settings button -->");
		out.println("					<div class=\"uk-button-group\">");
		out.println("						<li class=\"uk-parent\" data-uk-dropdown><i");
		out.println("							class=\"uk-icon-wrench uk-icon-medium\"></i>");
		out.println("							<div class=\"uk-dropdown uk-dropdown-navbar\">");
		out.println("								<ul class=\"uk-nav uk-nav-navbar\">");
		out.println("									<li><a class=\"\" href=\"#admin-login\" data-uk-modal>Admin");
		out.println("											Panel</a></li>");
		out.println("									<li class=\"uk-nav-divider\"></li>");
		out.println("									<li><form class=\"uk-form\" action=\"Logout\" method=\"GET\">");
		out.println("											<button type=\"submit\" class=\"uk-button uk-button-danger\">Logout</button>");
		out.println("										</form></li>");
		out.println("								</ul>");
		out.println("							</div></li>");
		out.println("					</div>");
		out.println("					<!-- end settings button -->");
		out.println("				</div>");
		out.println("				<!--search box-->");
		out.println("				<div class=\"uk-navbar-flip\">");
		out.println("					<div class=\"uk-navbar-content uk-hidden-small\">");
		out.println("						<form action=\"Search\" method=\"GET\"");
		out.println("							class=\"uk-search uk-form uk-margin-remove uk-display-inline-block\"");
		out.println("							data-uk-search=\"{flipDropdown:true}\">");
		out.println("							<input class=\"uk-search-field uk-text-center\" type=\"text\" "
				+ "onkeyup=\"ajaxFunction(this.value);\"");
		out.println("								name=\"movie\" placeholder=\"search...\">"
				+ "<div id=\"livesearch\"></div><INPUT");
		out.println("								TYPE=\"HIDDEN\" NAME=\"order\" VALUE=\"title\"> <INPUT");
		out.println("								TYPE=\"HIDDEN\" NAME=\"type\" VALUE=\"asc\"> <INPUT");
		out.println("								TYPE=\"HIDDEN\" NAME=\"page\" VALUE=\"0\"> <INPUT");
		out.println("								TYPE=\"HIDDEN\" NAME=\"rpp\" VALUE=\"5\">");
		out.println("							<button class=\"uk-search-close\" type=\"reset\"></button>");
		out.println("						</form>");
		out.println("					</div>");
		out.println("				</div>");
		out.println("				<!--search box end-->");
		out.println("			</nav>");
		out.println("		</div>");
		out.println("	</div>");
		out.println("	<!--end top nav, begin content-->");
	}

}